//
//  CSSTileAnimation.h
//  CodeSample
//
//  Created by Benjamin Pious on 3/24/14.
//  Copyright (c) 2014 benpious. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <GLKit/GLKit.h>

/**
 Contains information about an individual animation to be applied to a tile
 */
@interface CSSTileAnimation : NSObject

@property GLKMatrix4 beginningTransform;
@property GLKMatrix4 endingTransformation;
/**
 Generated by LERPing beginningTransform and endingTransform. As such it may cause distortions in the case of 
 rotation transformations.
 */
@property (readonly) GLKMatrix4 currentTransformation;
@property float animationTime;
@property float totalAnimationTime;

@end
